export type PricingPlan = {
  name: string;
  slug: string;
  monthlyPrice: number;
  storageLabel: string;
  segment: string;
  users: number;
  maxEmailsPerDay: number;
  fileTransferLabel: string;
  addonsIcon: string;
  addonsIconWidth: number;
  addonsIconHeight: number;
  addonsIconNames: string[];
  features: string[];
  popular?: boolean;
};

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: 'Starter',
    slug: 'starter',
    monthlyPrice: 5,
    storageLabel: '20 GB',
    segment: 'Small teams, startups',
    users: 10,
    maxEmailsPerDay: 50,
    fileTransferLabel: '5 GB',
    addonsIcon: '/assets/images/pricing/starter-addons.svg',
    addonsIconWidth: 148,
    addonsIconHeight: 37,
    addonsIconNames: ['Mail', 'Calender', 'Contact', 'Snaarpdrive'],
    features: ['10 users', '20 GB Shared Space', '50 emails per day', '5 GB file transfer', 'Email scheduling'],
  },
  {
    name: 'Growth',
    slug: 'growth',
    monthlyPrice: 25,
    storageLabel: '100 GB',
    segment: 'SMEs, agencies',
    users: 25,
    maxEmailsPerDay: 100,
    fileTransferLabel: '7 GB',
    addonsIcon: '/assets/images/pricing/growth-addons.svg',
    addonsIconWidth: 222,
    addonsIconHeight: 74,
    addonsIconNames: ['Mail', 'Calender', 'Contact', 'Snaarpdrive', 'Kalender', 'Snaarplock', 'Sheet', 'Document', 'Presentation'],
    features: ['25 users', '100 GB Shared Space', '100 emails per day', '7 GB file transfer', 'AI replies', 'Email scheduling'],
  },
  {
    name: 'Business',
    slug: 'business',
    monthlyPrice: 50,
    storageLabel: '250 GB',
    segment: 'Mid-sized organisations',
    users: 50,
    maxEmailsPerDay: 150,
    fileTransferLabel: '7 GB',
    addonsIcon: '/assets/images/pricing/business-addons.svg',
    addonsIconWidth: 222,
    addonsIconHeight: 74,
    addonsIconNames: [
      'Mail',
      'Calender',
      'Contact',
      'Snaarpdrive',
      'Kalender',
      'Snaarplock',
      'Sheet',
      'Document',
      'Presentation',
      'Teams',
      'Chat',
      'Ai Compose',
    ],
    features: ['50 users', '250 GB shared storage', '150 emails per day', '7 GB file transfer', 'AI replies', 'Email scheduling'],
    popular: true,
  },
  {
    name: 'Scale',
    slug: 'scale',
    monthlyPrice: 100,
    storageLabel: '1 TB',
    segment: 'Fast-growing companies',
    users: 100,
    maxEmailsPerDay: 200,
    fileTransferLabel: '10 GB',
    addonsIcon: '/assets/images/pricing/scale-addons.svg',
    addonsIconWidth: 222,
    addonsIconHeight: 111,
    addonsIconNames: [
      'Mail',
      'Calender',
      'Contact',
      'Snaarpdrive',
      'Kalender',
      'Snaarplock',
      'Sheet',
      'Document',
      'Presentation',
      'Teams',
      'Chat',
      'Meet',
      'Ai Compose',
      'Sendrit',
      'VerifyRit',
    ],
    features: ['100 users', '1 TB shared storage', '200 emails per day', '10 GB file transfer', 'AI replies', 'Email scheduling'],
  },
  {
    name: 'Enterprise',
    slug: 'enterprise',
    monthlyPrice: 200,
    storageLabel: '2.5 TB',
    segment: 'Large teams',
    users: 200,
    maxEmailsPerDay: 250,
    fileTransferLabel: '10 GB',
    addonsIcon: '/assets/images/pricing/enterprise-addons.svg',
    addonsIconWidth: 222,
    addonsIconHeight: 111,
    addonsIconNames: [
      'Mail',
      'Calender',
      'Contact',
      'Snaarpdrive',
      'Kalender',
      'Snaarplock',
      'Sheet',
      'Document',
      'Presentation',
      'Teams',
      'Chat',
      'Meet',
      'Ai Compose',
      'Sendrit',
      'VerifyRit',
      'CRM',
      'Zeus',
    ],
    features: ['200 users', '2.5 TB shared storage', '250 emails per day', '10 GB file transfer', 'AI replies', 'Email scheduling'],
  },
  {
    name: 'Corporate',
    slug: 'corporate',
    monthlyPrice: 500,
    storageLabel: '7 TB',
    segment: 'Data-heavy businesses',
    users: 500,
    maxEmailsPerDay: 300,
    fileTransferLabel: '12 GB',
    addonsIcon: '/assets/images/pricing/corporate-addons.svg',
    addonsIconWidth: 222,
    addonsIconHeight: 111,
    addonsIconNames: [
      'Mail',
      'Calender',
      'Contact',
      'Snaarpdrive',
      'Kalender',
      'Snaarplock',
      'Sheet',
      'Document',
      'Presentation',
      'Teams',
      'Chat',
      'Meet',
      'Ai Compose',
      'Sendrit',
      'VerifyRit',
      'CRM',
      'Zeus',
      'Snaarp Books',
    ],
    features: [
      '500 users',
      '7 TB shared storage',
      '300 emails per day',
      '12 GB file transfer',
      'AI replies',
      'Email support',
      'Spam protection',
      'Dedicated account manager',
      'Email scheduling',
    ],
  },
  {
    name: 'Ultra',
    slug: 'ultra',
    monthlyPrice: 2500,
    storageLabel: '35 TB',
    segment: 'Large enterprises',
    users: 2500,
    maxEmailsPerDay: 400,
    fileTransferLabel: '12 GB',
    addonsIcon: '/assets/images/pricing/ultra-addons.svg',
    addonsIconWidth: 222,
    addonsIconHeight: 148,
    addonsIconNames: [
      'Mail',
      'Calender',
      'Contact',
      'Snaarpdrive',
      'Kalender',
      'Snaarplock',
      'Sheet',
      'Document',
      'Presentation',
      'Teams',
      'Chat',
      'Meet',
      'Ai Compose',
      'Sendrit',
      'VerifyRit',
      'CRM',
      'Zeus',
      'Snaarp Books',
      'Neo Ai',
    ],
    features: [
      '2500 users',
      '35 TB shared storage',
      '400 emails per day',
      '12 GB file transfer',
      'AI replies',
      'Email support',
      'Spam protection',
      'Email scheduling',
    ],
  },
];

export const ANNUAL_DISCOUNT = 0.2;
