// AUTO-GENERATED from standalone "Snaarp Books Website.html" — do not edit by hand.
// The hero section is reconstructed in JSX (BooksPageClient) so the animated,
// server-rendered "Snaarp Books" app-tablet demo (BooksAppPreviewMockup) can
// sit in the mockup canvas. The phone beside it stays as-authored HTML.
/* eslint-disable */
export const BOOKS_HERO_DECO = `<div data-dc-tpl="49" style="position: absolute; right: -160px; top: 40px; width: 720px; height: 720px; border-radius: 50%; background: radial-gradient(circle, rgba(160, 140, 255, 0.16), rgba(160, 140, 255, 0) 70%); pointer-events: none;"></div>
  <div data-dc-tpl="50" style="position: absolute; right: 220px; top: -120px; width: 520px; height: 520px; border-radius: 50%; border: 1px solid rgba(120, 100, 240, 0.08); pointer-events: none;"></div>`;
export const BOOKS_HERO_TEXTCOL = `<div data-dc-tpl="52" class="books-hero-col" style="flex: 1 1 460px; min-width: 0px; max-width: 600px;">
      
      <h1 data-dc-tpl="59" class="books-hero-heading" style="margin: 0px; font-size: clamp(40px, 5.2vw, 62px); line-height: 1.04; letter-spacing: -0.035em; font-weight: 800; color: rgb(11, 13, 42); text-wrap: balance;">Less Bookkeeping.<br data-dc-tpl="60"><span data-dc-tpl="61" style="color: rgb(124, 58, 237);">More Business.</span></h1>
      <p data-dc-tpl="62" class="books-lede" style="margin: 22px 0px 0px; font-size: 16.5px; line-height: 1.6; color: rgb(75, 80, 112); max-width: 540px; text-wrap: pretty;">Everything your business needs to manage money, customers, invoices, expenses, banking, taxes and reports — all in one powerful platform. Save time, stay compliant and grow faster with Snaarp Books.</p>
      <div data-dc-tpl="63" style="margin-top: 26px; display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 14px 24px; max-width: 560px;">
        
          <div data-dc-tpl="65" style="display: flex; align-items: center; gap: 11px; font-size: 14.5px; color: rgb(42, 46, 77); font-weight: 500;">
            <span data-dc-tpl="66" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(124, 58, 237); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="67" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Simple to use</span>
          </div>
        
          <div data-dc-tpl="65" style="display: flex; align-items: center; gap: 11px; font-size: 14.5px; color: rgb(42, 46, 77); font-weight: 500;">
            <span data-dc-tpl="66" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(124, 58, 237); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="67" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">HMRC ready (VAT, MTD, CIS)</span>
          </div>
        
          <div data-dc-tpl="65" style="display: flex; align-items: center; gap: 11px; font-size: 14.5px; color: rgb(42, 46, 77); font-weight: 500;">
            <span data-dc-tpl="66" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(124, 58, 237); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="67" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Works on all devices</span>
          </div>
        
          <div data-dc-tpl="65" style="display: flex; align-items: center; gap: 11px; font-size: 14.5px; color: rgb(42, 46, 77); font-weight: 500;">
            <span data-dc-tpl="66" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(124, 58, 237); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="67" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Tax reserved register</span>
          </div>
        
          <div data-dc-tpl="65" style="display: flex; align-items: center; gap: 11px; font-size: 14.5px; color: rgb(42, 46, 77); font-weight: 500;">
            <span data-dc-tpl="66" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(124, 58, 237); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="67" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">No credit card required</span>
          </div>
        
          <div data-dc-tpl="65" style="display: flex; align-items: center; gap: 11px; font-size: 14.5px; color: rgb(42, 46, 77); font-weight: 500;">
            <span data-dc-tpl="66" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(124, 58, 237); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="67" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">14-day free trial</span>
          </div>
        
      </div>
      <div data-dc-tpl="68" style="margin-top: 34px; display: flex; flex-wrap: wrap; gap: 16px;">
        <button data-dc-tpl="69" class="scp5" style="white-space: nowrap; height: 56px; padding: 0px 44px; border-radius: 10px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(124, 58, 237); color: rgb(255, 255, 255); font-weight: 600; font-size: 15.5px; cursor: pointer; display: flex; align-items: center; gap: 12px; box-shadow: rgba(124, 58, 237, 0.65) 0px 14px 30px -10px; transition: transform 0.2s, background 0.2s;">Get Started Free <span data-dc-tpl="70" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 20px; line-height: 1;">arrow_forward</span></button>
        <button data-dc-tpl="71" class="scp6" style="white-space: nowrap; height: 56px; padding: 0px 40px; border-radius: 10px; border: 1.5px solid rgb(183, 166, 255); background: rgb(255, 255, 255); color: rgb(124, 58, 237); font-weight: 600; font-size: 15.5px; cursor: pointer; display: flex; align-items: center; gap: 12px; transition: 0.2s;">
          <span data-dc-tpl="72" style="width: 26px; height: 26px; border-radius: 50%; border: 2px solid rgb(124, 58, 237); display: grid; place-items: center;"><span data-dc-tpl="73" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 16px; line-height: 1;">play_arrow</span></span>Watch Demo</button>
      </div>
      <div data-dc-tpl="74" style="margin-top: 32px; display: flex; align-items: center; gap: 14px;">
        <div data-dc-tpl="75" style="display: flex; align-items: center;">
          <img src="/assets/books/avatar-1.png" alt="Customer" style="width: 44px; height: 44px; border-radius: 50%; object-fit: cover; border: 2.5px solid #fff; box-shadow: rgba(30,20,90,0.12) 0px 3px 8px;">
          <img src="/assets/books/avatar-2.png" alt="Customer" style="width: 44px; height: 44px; border-radius: 50%; object-fit: cover; border: 2.5px solid #fff; box-shadow: rgba(30,20,90,0.12) 0px 3px 8px; margin-left: -14px;">
          <img src="/assets/books/avatar-3.png" alt="Customer" style="width: 44px; height: 44px; border-radius: 50%; object-fit: cover; border: 2.5px solid #fff; box-shadow: rgba(30,20,90,0.12) 0px 3px 8px; margin-left: -14px;">
          <img src="/assets/books/avatar-4.png" alt="Customer" style="width: 44px; height: 44px; border-radius: 50%; object-fit: cover; border: 2.5px solid #fff; box-shadow: rgba(30,20,90,0.12) 0px 3px 8px; margin-left: -14px;">
        </div>
        <div data-dc-tpl="76" style="display: flex; flex-direction: column; gap: 3px;">
          <span data-dc-tpl="77" style="display: flex; gap: 1px; color: rgb(245, 180, 0);"><span data-dc-tpl="78" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">star</span><span data-dc-tpl="79" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">star</span><span data-dc-tpl="80" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">star</span><span data-dc-tpl="81" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">star</span><span data-dc-tpl="82" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">star</span></span>
          <span data-dc-tpl="83" style="font-size: 13.5px; color: rgb(90, 95, 125); line-height: 1.35;">Trusted by <b data-dc-tpl="84" style="color: rgb(11, 13, 42);">10,000+ businesses</b><br data-dc-tpl="85">worldwide</span>
        </div>
      </div>
    </div>`;
export const BOOKS_HERO_PHONE = `<div data-dc-tpl="165" style="position: absolute; left: 532px; top: 128px; width: 204px; height: 420px; border-radius: 40px; background: linear-gradient(150deg, rgb(90, 90, 102) 0%, rgb(31, 31, 37) 30%, rgb(52, 52, 60) 70%, rgb(20, 20, 24) 100%); padding: 3px; box-shadow: rgba(40, 20, 130, 0.55) 0px 40px 70px -24px, rgba(20, 10, 60, 0.4) 0px 12px 24px -12px;">
          <span data-dc-tpl="166" style="position: absolute; left: -2px; top: 92px; width: 3px; height: 24px; border-radius: 2px; background: rgb(42, 42, 49);"></span>
          <span data-dc-tpl="167" style="position: absolute; left: -2px; top: 126px; width: 3px; height: 38px; border-radius: 2px; background: rgb(42, 42, 49);"></span>
          <span data-dc-tpl="168" style="position: absolute; right: -2px; top: 120px; width: 3px; height: 52px; border-radius: 2px; background: rgb(42, 42, 49);"></span>
          <div data-dc-tpl="169" style="position: relative; width: 100%; height: 100%; border-radius: 37px; background: rgb(8, 8, 10); padding: 7px;">
            <div data-dc-tpl="170" style="position: relative; width: 100%; height: 100%; border-radius: 31px; background: rgb(255, 255, 255); overflow: hidden; display: flex; flex-direction: column;">
              <span data-dc-tpl="171" style="position: absolute; top: 8px; left: 50%; margin-left: -34px; width: 68px; height: 20px; border-radius: 12px; background: rgb(0, 0, 0); z-index: 2;"></span>
              <div data-dc-tpl="172" style="height: 34px; display: flex; align-items: center; justify-content: space-between; padding: 4px 18px 0px 22px; font-size: 10px; font-weight: 700; flex: 0 0 auto;"><span data-dc-tpl="173">9:41</span><span data-dc-tpl="174" style="display: flex; gap: 2px; align-items: center;"><span data-dc-tpl="175" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 11px; line-height: 1;">signal_cellular_alt</span><span data-dc-tpl="176" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 11px; line-height: 1;">wifi</span><span data-dc-tpl="177" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 12px; line-height: 1; transform: rotate(90deg);">battery_full</span></span></div>
              <div data-dc-tpl="178" style="padding: 8px 14px 0px; display: flex; align-items: center; justify-content: space-between;"><span data-dc-tpl="179" style="display: flex; align-items: center; gap: 6px;"><span data-dc-tpl="180" style="width: 18px; height: 18px; border-radius: 5px; background: rgb(238, 233, 255); display: grid; place-items: center; color: rgb(124, 58, 237);"><span data-dc-tpl="181" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 12px; line-height: 1;">auto_stories</span></span><span data-dc-tpl="182" style="font-weight: 800; font-size: 12px; letter-spacing: -0.05em;">snaarp</span></span><span data-dc-tpl="183" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(140, 144, 168);">notifications</span></div>
              <div data-dc-tpl="184" style="margin: 14px 12px 0px; padding: 12px; border-radius: 12px; background: linear-gradient(145deg, rgb(246, 243, 255), rgb(238, 233, 255));">
                <div data-dc-tpl="185" style="font-size: 8.5px; color: rgb(107, 112, 144); font-weight: 600;">Total Balance</div>
                <div data-dc-tpl="186" style="font-size: 18px; font-weight: 800; letter-spacing: -0.03em; margin-top: 3px;">£550,000.00</div>
                <div data-dc-tpl="187" style="display: flex; align-items: center; gap: 3px; font-size: 8px; color: rgb(22, 163, 74); font-weight: 700; margin-top: 3px;"><span data-dc-tpl="188" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 10px; line-height: 1;">north</span>12% this month</div>
              </div>
              <div data-dc-tpl="189" style="padding: 12px 12px 0px; display: flex; flex-direction: column; gap: 7px;">
                
                  <div data-dc-tpl="191" class="scp7" style="display: flex; align-items: center; gap: 9px; padding: 8px 9px; border-radius: 10px; border: 1px solid rgb(240, 239, 246); background: rgb(255, 255, 255); box-shadow: rgba(30, 20, 90, 0.04) 0px 2px 6px; cursor: pointer; font-size: 9.5px; font-weight: 600; white-space: nowrap;">
                    <span data-dc-tpl="192" style="width: 22px; height: 22px; border-radius: 7px; display: grid; place-items: center; background: rgb(232, 240, 255); color: rgb(37, 99, 235);"><span data-dc-tpl="193" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1;"><span class="sc-interp">description</span></span></span><span class="sc-interp">Create Invoice</span><span data-dc-tpl="194" style="margin-left: auto; font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1; color: rgb(195, 198, 214);">chevron_right</span>
                  </div>
                
                  <div data-dc-tpl="191" class="scp7" style="display: flex; align-items: center; gap: 9px; padding: 8px 9px; border-radius: 10px; border: 1px solid rgb(240, 239, 246); background: rgb(255, 255, 255); box-shadow: rgba(30, 20, 90, 0.04) 0px 2px 6px; cursor: pointer; font-size: 9.5px; font-weight: 600; white-space: nowrap;">
                    <span data-dc-tpl="192" style="width: 22px; height: 22px; border-radius: 7px; display: grid; place-items: center; background: rgb(227, 248, 234); color: rgb(22, 163, 74);"><span data-dc-tpl="193" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1;"><span class="sc-interp">payments</span></span></span><span class="sc-interp">Add Expense</span><span data-dc-tpl="194" style="margin-left: auto; font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1; color: rgb(195, 198, 214);">chevron_right</span>
                  </div>
                
                  <div data-dc-tpl="191" class="scp7" style="display: flex; align-items: center; gap: 9px; padding: 8px 9px; border-radius: 10px; border: 1px solid rgb(240, 239, 246); background: rgb(255, 255, 255); box-shadow: rgba(30, 20, 90, 0.04) 0px 2px 6px; cursor: pointer; font-size: 9.5px; font-weight: 600; white-space: nowrap;">
                    <span data-dc-tpl="192" style="width: 22px; height: 22px; border-radius: 7px; display: grid; place-items: center; background: rgb(238, 233, 255); color: rgb(124, 58, 237);"><span data-dc-tpl="193" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1;"><span class="sc-interp">account_balance</span></span></span><span class="sc-interp">Connect Bank</span><span data-dc-tpl="194" style="margin-left: auto; font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1; color: rgb(195, 198, 214);">chevron_right</span>
                  </div>
                
                  <div data-dc-tpl="191" class="scp7" style="display: flex; align-items: center; gap: 9px; padding: 8px 9px; border-radius: 10px; border: 1px solid rgb(240, 239, 246); background: rgb(255, 255, 255); box-shadow: rgba(30, 20, 90, 0.04) 0px 2px 6px; cursor: pointer; font-size: 9.5px; font-weight: 600; white-space: nowrap;">
                    <span data-dc-tpl="192" style="width: 22px; height: 22px; border-radius: 7px; display: grid; place-items: center; background: rgb(243, 232, 255); color: rgb(124, 58, 237);"><span data-dc-tpl="193" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1;"><span class="sc-interp">monitoring</span></span></span><span class="sc-interp">View Reports</span><span data-dc-tpl="194" style="margin-left: auto; font-family: &quot;Material Symbols Rounded&quot;; font-size: 13px; line-height: 1; color: rgb(195, 198, 214);">chevron_right</span>
                  </div>
                
              </div>
              <div data-dc-tpl="195" style="margin-top: auto; border-top: 1px solid rgb(240, 239, 246); display: grid; grid-template-columns: repeat(4, 1fr); padding: 7px 4px 16px; position: relative;">
                
                  <div data-dc-tpl="197" style="display: flex; flex-direction: column; align-items: center; gap: 2px; font-size: 7px; font-weight: 600; color: rgb(124, 58, 237);"><span data-dc-tpl="198" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1;"><span class="sc-interp">home</span></span><span class="sc-interp">Home</span></div>
                
                  <div data-dc-tpl="197" style="display: flex; flex-direction: column; align-items: center; gap: 2px; font-size: 7px; font-weight: 600; color: rgb(163, 167, 189);"><span data-dc-tpl="198" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1;"><span class="sc-interp">description</span></span><span class="sc-interp">Invoices</span></div>
                
                  <div data-dc-tpl="197" style="display: flex; flex-direction: column; align-items: center; gap: 2px; font-size: 7px; font-weight: 600; color: rgb(163, 167, 189);"><span data-dc-tpl="198" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1;"><span class="sc-interp">receipt_long</span></span><span class="sc-interp">Expenses</span></div>
                
                  <div data-dc-tpl="197" style="display: flex; flex-direction: column; align-items: center; gap: 2px; font-size: 7px; font-weight: 600; color: rgb(163, 167, 189);"><span data-dc-tpl="198" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1;"><span class="sc-interp">more_horiz</span></span><span class="sc-interp">More</span></div>
                
                <span data-dc-tpl="199" style="position: absolute; bottom: 5px; left: 50%; margin-left: -32px; width: 64px; height: 3.5px; border-radius: 3px; background: rgb(11, 13, 42);"></span>
              </div>
            </div>
          </div>
        </div>`;
export const BOOKS_AFTER_HERO_PRE = `<section data-dc-tpl="200" style="background: rgb(255, 255, 255); border-top: 1px solid rgb(240, 239, 246); border-bottom: 1px solid rgb(240, 239, 246);">
  <div data-dc-tpl="201" class="books-container" style="max-width: 1280px; margin: 0px auto; padding: 30px clamp(20px, 4vw, 48px) 36px;">
    <div data-dc-tpl="202" style="text-align: center; font-size: 12.5px; letter-spacing: 0.18em; font-weight: 600; color: rgb(122, 127, 160); text-transform: uppercase;">Trusted by businesses of all sizes</div>
    <div data-dc-tpl="203" style="margin-top: 26px; display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 28px 36px;">
      <img data-dc-tpl="204" src="/assets/books/brands/aosmith.svg" alt="A.O. Smith" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="205" src="/assets/books/brands/amgen.svg" alt="Amgen" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="206" src="/assets/books/brands/biogen.svg" alt="Biogen" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="207" src="/assets/books/brands/celanese.svg" alt="Celanese" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="212" src="/assets/books/brands/dow.svg" alt="Dow" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="213" src="/assets/books/brands/exelon.svg" alt="Exelon" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="215" src="/assets/books/brands/lowes.svg" alt="Lowe's" style="height: 30px; width: auto; object-fit: contain;">
      <img data-dc-tpl="220" src="/assets/books/brands/realty.svg" alt="Realty Income" style="height: 30px; width: auto; object-fit: contain;">
    </div>
  </div></section><section data-dc-tpl="225" style="background: linear-gradient(rgb(245, 244, 251), rgb(248, 247, 253));">
  <div data-dc-tpl="226" class="books-container" style="max-width: 1280px; margin: 0px auto; padding: 44px clamp(20px, 4vw, 48px) 48px; display: grid; grid-template-columns: repeat(auto-fit, minmax(138px, 1fr)); gap: 28px 18px;">
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(238, 233, 255); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(109, 75, 255) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(109, 75, 255); box-shadow: rgb(109, 75, 255) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">description</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Invoicing</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">Create and send professional invoices in seconds.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(227, 248, 234); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(34, 181, 94) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(34, 181, 94); box-shadow: rgb(34, 181, 94) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">receipt_long</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Expenses</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">Capture receipts, track and categorise expenses.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(230, 238, 255); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(37, 99, 235) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(37, 99, 235); box-shadow: rgb(37, 99, 235) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">account_balance</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Banking</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">Connect your bank accounts and reconcile automatically.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(255, 238, 226); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(249, 115, 22) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(249, 115, 22); box-shadow: rgb(249, 115, 22) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">shopping_cart</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Purchases</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">Manage bills, vendors and purchase orders.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(241, 233, 255); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(124, 58, 237) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(124, 58, 237); box-shadow: rgb(124, 58, 237) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">verified_user</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Tax &amp; Compliance</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">VAT, MTD, CIS and more. Stay compliant effortlessly.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(230, 238, 255); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(37, 99, 235) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(37, 99, 235); box-shadow: rgb(37, 99, 235) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">bar_chart</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Reports</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">50+ financial reports and real-time insights.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(227, 248, 234); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(22, 163, 74) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(22, 163, 74); box-shadow: rgb(22, 163, 74) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">storefront</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Customer Portals</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">Let customers view and pay online.</span></div>
      </div>
    
      <div data-dc-tpl="228" class="scp8" style="display: flex; flex-direction: column; align-items: center; text-align: center; padding: 10px 6px; border-radius: 16px; transition: 0.25s; cursor: default;">
        <span data-dc-tpl="229" style="width: 74px; height: 74px; border-radius: 18px; display: grid; place-items: center; background: rgb(238, 233, 255); box-shadow: rgba(255, 255, 255, 0.7) 0px 0px 0px 1px inset, rgb(109, 75, 255) 0px 10px 22px -14px;"><span data-dc-tpl="230" style="width: 40px; height: 40px; border-radius: 11px; display: grid; place-items: center; background: rgb(109, 75, 255); box-shadow: rgb(109, 75, 255) 0px 6px 12px -4px;"><span data-dc-tpl="231" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1; color: rgb(255, 255, 255);"><span class="sc-interp">folder_managed</span></span></span></span>
        <div data-dc-tpl="232" style="margin-top: 16px; font-weight: 700; font-size: 15px; color: rgb(11, 13, 42);"><span class="sc-interp">Projects</span></div>
        <div data-dc-tpl="233" style="margin-top: 8px; font-size: 12.5px; line-height: 1.5; color: rgb(90, 95, 125); max-width: 150px;"><span class="sc-interp">Track time, costs and profitability by project.</span></div>
      </div>
    
  </div></section>`;
export const BOOKS_EYN_TEXTCOL = `<div data-dc-tpl="236" style="flex: 1 1 400px; min-width: 0px; max-width: 500px;">
      <div data-dc-tpl="237" style="font-size: 12px; letter-spacing: 0.16em; font-weight: 600; color: rgb(122, 127, 160); text-transform: uppercase;">All-in-one accounting solution</div>
      <h2 data-dc-tpl="238" style="margin: 18px 0px 0px; font-size: clamp(32px, 3.6vw, 44px); line-height: 1.1; letter-spacing: -0.03em; font-weight: 800;">Everything You Need.<br data-dc-tpl="239"><span data-dc-tpl="240" style="color: rgb(124, 58, 237);">In One Place.</span></h2>
      <p data-dc-tpl="241" style="margin: 20px 0px 0px; font-size: 16.5px; line-height: 1.6; color: rgb(75, 80, 112); text-wrap: pretty;">From invoicing to tax, Snaarp Books brings your financials together so you can focus on what matters most — growing your business.</p>
      <div data-dc-tpl="242" style="margin-top: 24px; display: flex; flex-direction: column; gap: 14px;">
        
          <div data-dc-tpl="244" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="245" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="246" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Automate repetitive tasks</span></div>
        
          <div data-dc-tpl="244" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="245" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="246" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Stay compliant with HMRC &amp; MTD</span></div>
        
          <div data-dc-tpl="244" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="245" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="246" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Get real-time financial insights</span></div>
        
          <div data-dc-tpl="244" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="245" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="246" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Access your data anywhere, anytime</span></div>
        
      </div>
      <div data-dc-tpl="247" style="margin-top: 44px; margin-left: 40px; display: flex; align-items: flex-start; gap: 10px; color: rgb(124, 58, 237);">
        <svg data-dc-tpl="248" width="64" height="40" style="flex: 0 0 auto; margin-top: 6px;"><path data-dc-tpl="249" d="M60 8 C 42 30, 20 32, 6 20" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.8; stroke-linecap: round;"></path><path data-dc-tpl="250" d="M14 14 L5 20 L15 25" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.8; stroke-linecap: round; stroke-linejoin: round;"></path></svg>
        <span data-dc-tpl="251" style="font-family: Caveat, cursive; font-size: 25px; line-height: 1.05; transform: rotate(-6deg); display: block; font-weight: 600;">Powerful dashboard<br data-dc-tpl="252">for better decisions</span>
      </div>
    </div>`;
export const BOOKS_EYN_SECTION_STYLE = "background: radial-gradient(700px 500px at 75% 50%, rgb(239, 235, 255), rgba(239, 235, 255, 0) 70%), rgb(250, 250, 254);";
export const BOOKS_MOBILE_TEXTCOL = `<div data-dc-tpl="412" style="flex: 1 1 400px; min-width: 0px; max-width: 540px; position: relative;">
        <div data-dc-tpl="413" style="font-size: 12px; letter-spacing: 0.16em; font-weight: 600; color: rgb(122, 127, 160); text-transform: uppercase;">Mobile on the go</div>
        <h2 data-dc-tpl="414" style="margin: 16px 0px 0px; font-size: clamp(30px, 3.4vw, 42px); line-height: 1.12; letter-spacing: -0.03em; font-weight: 800; color: rgb(18, 19, 74);">Manage Your Business<br data-dc-tpl="415">From <span data-dc-tpl="416" style="color: rgb(124, 58, 237);">Anywhere.</span></h2>
        <p data-dc-tpl="417" style="margin: 18px 0px 0px; font-size: 16px; line-height: 1.6; color: rgb(75, 80, 112); text-wrap: pretty;">The Snaarp Books mobile app gives you full control of your finances, wherever you are. Send invoices, track expenses, check your bank balance and more — all from your phone.</p>
        <div data-dc-tpl="418" style="margin-top: 22px; display: flex; flex-direction: column; gap: 13px;">
          
            <div data-dc-tpl="420" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="421" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="422" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Create and send invoices</span></div>
          
            <div data-dc-tpl="420" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="421" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="422" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Track expenses and receipts</span></div>
          
            <div data-dc-tpl="420" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="421" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="422" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">View real-time reports</span></div>
          
            <div data-dc-tpl="420" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="421" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="422" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Secure and fast access</span></div>
          
        </div>
        <div data-dc-tpl="423" style="margin-top: 28px; display: flex; flex-wrap: wrap; gap: 12px;">
          <a data-dc-tpl="424" href="#" class="scpa" style="height: 46px; padding: 0px 16px; border-radius: 9px; background: rgb(11, 11, 15); color: rgb(255, 255, 255); display: flex; align-items: center; gap: 9px; border: 1px solid rgb(42, 42, 49);"><span data-dc-tpl="425" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 26px; line-height: 1;">phone_iphone</span><span data-dc-tpl="426" style="display: flex; flex-direction: column; line-height: 1.05;"><span data-dc-tpl="427" style="font-size: 9px; opacity: 0.85;">Download on the</span><span data-dc-tpl="428" style="font-size: 17px; font-weight: 600; letter-spacing: -0.02em;">App Store</span></span></a>
          <a data-dc-tpl="429" href="#" class="scpa" style="height: 46px; padding: 0px 16px; border-radius: 9px; background: rgb(11, 11, 15); color: rgb(255, 255, 255); display: flex; align-items: center; gap: 9px; border: 1px solid rgb(42, 42, 49);"><svg data-dc-tpl="430" width="22" height="24"><polygon data-dc-tpl="431" points="1,1 13,12 1,23" style="fill: rgb(0, 210, 255);"></polygon><polygon data-dc-tpl="432" points="1,1 17,8 13,12" style="fill: rgb(0, 240, 118);"></polygon><polygon data-dc-tpl="433" points="1,23 13,12 17,16" style="fill: rgb(248, 59, 78);"></polygon><polygon data-dc-tpl="434" points="13,12 17,8 21,12 17,16" style="fill: rgb(255, 199, 0);"></polygon></svg><span data-dc-tpl="435" style="display: flex; flex-direction: column; line-height: 1.05;"><span data-dc-tpl="436" style="font-size: 9px; opacity: 0.85;">GET IT ON</span><span data-dc-tpl="437" style="font-size: 17px; font-weight: 600; letter-spacing: -0.02em;">Google Play</span></span></a>
        </div>
        <div data-dc-tpl="438" style="position: absolute; right: -6px; top: 52%; display: flex; align-items: flex-start; gap: 6px; pointer-events: none;">
          <svg data-dc-tpl="439" width="44" height="40"><path data-dc-tpl="440" d="M4 4 C 8 22, 22 32, 38 30" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.6; stroke-linecap: round;"></path><path data-dc-tpl="441" d="M31 25 L39 30 L31 35" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.6; stroke-linecap: round; stroke-linejoin: round;"></path></svg>
          <span data-dc-tpl="442" style="font-family: Caveat, cursive; font-size: 22px; line-height: 1.1; color: rgb(124, 58, 237); transform: rotate(-5deg); display: block; margin-top: 22px; font-weight: 600;">Your business<br data-dc-tpl="443">in your pocket</span>
        </div>
      </div>`;
export const BOOKS_MOBILE_SECTION_STYLE = "background: rgb(250, 250, 254);";
export const BOOKS_AFTER_MOBILE = `<section data-dc-tpl="444" data-screen-label="All-in-one banner" style="position: relative; overflow: hidden; background: radial-gradient(700px 500px at 72% 45%, rgba(90, 70, 255, 0.45), rgba(90, 70, 255, 0) 65%), radial-gradient(500px 400px at 5% 10%, rgba(120, 80, 255, 0.25), rgba(120, 80, 255, 0) 70%), linear-gradient(115deg, rgb(23, 13, 99) 0%, rgb(36, 21, 154) 45%, rgb(20, 11, 88) 100%); color: rgb(255, 255, 255);">
  <div data-dc-tpl="444b" style="position: absolute; inset: 0px; background-image: url(/assets/books/entrepreneur-forecasts.jpg); background-size: cover; background-position: center right; opacity: 0.55; pointer-events: none;"></div>
  <div data-dc-tpl="444c" style="position: absolute; inset: 0px; background: linear-gradient(100deg, rgba(23, 13, 99, 0.96) 0%, rgba(30, 17, 130, 0.88) 30%, rgba(36, 21, 154, 0.55) 58%, rgba(36, 21, 154, 0.28) 100%); pointer-events: none;"></div>
  <div data-dc-tpl="445" style="position: absolute; inset: 0px; background: repeating-linear-gradient(90deg, rgba(255, 255, 255, 0.024) 0px, rgba(255, 255, 255, 0.024) 1px, transparent 1px, transparent 64px); pointer-events: none;"></div>
  <div data-dc-tpl="446" class="books-container" style="position: relative; max-width: 1280px; margin: 0px auto; padding: clamp(56px, 7vw, 76px) clamp(20px, 4vw, 48px) 0px; display: flex; flex-wrap: wrap; gap: 40px; align-items: stretch;">
    <div data-dc-tpl="447" style="flex: 1 1 480px; min-width: 0px; max-width: 640px; padding-bottom: clamp(48px, 6vw, 72px);">
      <div data-dc-tpl="448" style="font-size: 13px; letter-spacing: 0.16em; font-weight: 600; color: rgb(185, 176, 255);">POWERFUL. SIMPLE. COMPLETE.</div>
      <h2 data-dc-tpl="449" style="margin: 16px 0px 0px; font-size: clamp(36px, 4.4vw, 56px); line-height: 1.08; letter-spacing: -0.035em; font-weight: 800; text-wrap: balance;">The All-in-One Accounting Solution for <span data-dc-tpl="450" style="color: rgb(46, 230, 242);">Modern Business.</span></h2>
      <p data-dc-tpl="451" style="margin: 20px 0px 0px; font-size: 17px; line-height: 1.6; color: rgb(227, 224, 255); max-width: 560px;">Stop juggling spreadsheets and multiple tools. Snaarp Books brings everything together so you can focus on what really matters — growing your business.</p>
      <div data-dc-tpl="452" style="margin-top: 32px; display: flex; flex-wrap: wrap; gap: 18px;">
        <button data-dc-tpl="453" class="scpb" style="white-space: nowrap; height: 60px; padding: 0px 44px; border-radius: 10px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(106, 59, 255); color: rgb(255, 255, 255); font-weight: 600; font-size: 16px; cursor: pointer; display: flex; align-items: center; gap: 12px; box-shadow: rgba(120, 80, 255, 0.9) 0px 16px 34px -12px, rgba(255, 255, 255, 0.2) 0px 1px 0px inset;">Get Started Free <span data-dc-tpl="454" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 20px; line-height: 1;">arrow_forward</span></button>
        <button data-dc-tpl="455" class="scpc" style="white-space: nowrap; height: 60px; padding: 0px 44px; border-radius: 10px; border: 1.5px solid rgba(255, 255, 255, 0.7); background: transparent; color: rgb(255, 255, 255); font-weight: 600; font-size: 16px; cursor: pointer; display: flex; align-items: center; gap: 12px;"><span data-dc-tpl="456" style="width: 28px; height: 28px; border-radius: 50%; border: 2px solid rgb(255, 255, 255); display: grid; place-items: center;"><span data-dc-tpl="457" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 17px; line-height: 1;">play_arrow</span></span>Watch Video</button>
      </div>
      <div data-dc-tpl="458" style="margin-top: 30px; display: flex; flex-wrap: wrap; gap: 14px 30px;">
        
          <div data-dc-tpl="460" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255); font-weight: 500;"><span data-dc-tpl="461" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(123, 80, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="462" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Set up in minutes</span></div>
        
          <div data-dc-tpl="460" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255); font-weight: 500;"><span data-dc-tpl="461" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(123, 80, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="462" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">No credit card required</span></div>
        
          <div data-dc-tpl="460" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255); font-weight: 500;"><span data-dc-tpl="461" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(123, 80, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="462" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Cancel anytime</span></div>
        
      </div>
    </div>
    <div data-dc-tpl="463" style="flex: 1 1 520px; min-width: 0px; position: relative; display: flex; align-items: center; min-height: 520px;">
      
      <div data-dc-tpl="466" style="position: relative; display: flex; flex-direction: column; gap: 18px; width: 100%; max-width: 350px; padding-bottom: 40px;">
        
          <div data-dc-tpl="468" class="scpd" style="display: flex; gap: 18px; align-items: center; padding: 24px 22px; border-radius: 16px; background: linear-gradient(135deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.05)); border: 1px solid rgba(255, 255, 255, 0.18); backdrop-filter: blur(14px); box-shadow: rgba(0, 0, 0, 0.5) 0px 20px 40px -20px, rgba(255, 255, 255, 0.15) 0px 1px 0px inset; transition: transform 0.25s;">
            <span data-dc-tpl="469" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 40px; line-height: 1; color: rgb(251, 191, 36); filter: drop-shadow(rgb(251, 191, 36) 0px 4px 10px); flex: 0 0 auto;"><span class="sc-interp">bolt</span></span>
            <span data-dc-tpl="470" style="display: flex; flex-direction: column; gap: 6px;"><span data-dc-tpl="471" style="font-weight: 700; font-size: 18px;"><span class="sc-interp">Save Hours</span></span><span data-dc-tpl="472" style="font-size: 13.5px; line-height: 1.5; color: rgb(214, 210, 255);"><span class="sc-interp">Automate repetitive tasks and eliminate manual work.</span></span></span>
          </div>
        
          <div data-dc-tpl="468" class="scpd" style="display: flex; gap: 18px; align-items: center; padding: 24px 22px; border-radius: 16px; background: linear-gradient(135deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.05)); border: 1px solid rgba(255, 255, 255, 0.18); backdrop-filter: blur(14px); box-shadow: rgba(0, 0, 0, 0.5) 0px 20px 40px -20px, rgba(255, 255, 255, 0.15) 0px 1px 0px inset; transition: transform 0.25s;">
            <span data-dc-tpl="469" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 40px; line-height: 1; color: rgb(56, 189, 248); filter: drop-shadow(rgb(56, 189, 248) 0px 4px 10px); flex: 0 0 auto;"><span class="sc-interp">bar_chart</span></span>
            <span data-dc-tpl="470" style="display: flex; flex-direction: column; gap: 6px;"><span data-dc-tpl="471" style="font-weight: 700; font-size: 18px;"><span class="sc-interp">Get Paid Faster</span></span><span data-dc-tpl="472" style="font-size: 13.5px; line-height: 1.5; color: rgb(214, 210, 255);"><span class="sc-interp">Professional invoices and online payments.</span></span></span>
          </div>
        
          <div data-dc-tpl="468" class="scpd" style="display: flex; gap: 18px; align-items: center; padding: 24px 22px; border-radius: 16px; background: linear-gradient(135deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.05)); border: 1px solid rgba(255, 255, 255, 0.18); backdrop-filter: blur(14px); box-shadow: rgba(0, 0, 0, 0.5) 0px 20px 40px -20px, rgba(255, 255, 255, 0.15) 0px 1px 0px inset; transition: transform 0.25s;">
            <span data-dc-tpl="469" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 40px; line-height: 1; color: rgb(34, 197, 94); filter: drop-shadow(rgb(34, 197, 94) 0px 4px 10px); flex: 0 0 auto;"><span class="sc-interp">verified_user</span></span>
            <span data-dc-tpl="470" style="display: flex; flex-direction: column; gap: 6px;"><span data-dc-tpl="471" style="font-weight: 700; font-size: 18px;"><span class="sc-interp">Stay Compliant</span></span><span data-dc-tpl="472" style="font-size: 13.5px; line-height: 1.5; color: rgb(214, 210, 255);"><span class="sc-interp">Built for UK businesses with HMRC-ready features.</span></span></span>
          </div>
        
      </div>
    </div>
  </div></section><section data-dc-tpl="473" style="background: rgb(250, 250, 254);">
  <div data-dc-tpl="474" class="books-container" style="max-width: 1280px; margin: 0px auto; padding: clamp(40px, 5vw, 56px) clamp(20px, 4vw, 48px) 0px; display: flex; flex-wrap: wrap; gap: 28px;">
    <div data-dc-tpl="475" style="flex: 1 1 360px; min-width: 0px; max-width: 460px; border-radius: 20px; background: linear-gradient(145deg, rgb(241, 238, 253), rgb(248, 247, 253)); border: 1px solid rgb(236, 232, 251); padding: 28px 32px;">
      <span data-dc-tpl="476" style="font-family: Georgia, serif; font-size: 64px; line-height: 0.6; color: rgb(196, 200, 218); font-weight: 700; display: block; height: 30px;">“</span>
      <p data-dc-tpl="477" style="margin: 14px 0px 0px; font-size: 20px; line-height: 1.45; color: rgb(11, 13, 42); font-weight: 500; text-wrap: pretty;">“Snaarp Books has transformed the way we manage our finances. We save hours every month and our accounts are always up to date.”</p>
      <div data-dc-tpl="478" style="margin-top: 22px; display: flex; align-items: center; gap: 16px;">
        <img data-dc-tpl="479" src="/assets/books/avatar-testimonial.png" alt="Mateo Rossi" style="width: 66px; height: 66px; border-radius: 50%; object-fit: cover; box-shadow: rgb(255, 255, 255) 0px 0px 0px 3px;">
        <div data-dc-tpl="480"><div data-dc-tpl="481" style="font-weight: 700; font-size: 16.5px;">Mateo Rossi</div><div data-dc-tpl="482" style="font-size: 14px; color: rgb(90, 95, 125); margin-top: 2px;">Founder, GrowthLab</div><div data-dc-tpl="483" style="display: flex; gap: 1px; color: rgb(245, 180, 0); margin-top: 5px;"><span data-dc-tpl="484" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 19px; line-height: 1;">star</span><span data-dc-tpl="485" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 19px; line-height: 1;">star</span><span data-dc-tpl="486" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 19px; line-height: 1;">star</span><span data-dc-tpl="487" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 19px; line-height: 1;">star</span><span data-dc-tpl="488" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 19px; line-height: 1;">star</span></div></div>
      </div>
    </div>
    <div data-dc-tpl="489" style="flex: 2 1 560px; min-width: 0px; border-radius: 20px; background: rgb(255, 255, 255); border: 1px solid rgb(236, 235, 245); box-shadow: rgba(40, 20, 130, 0.2) 0px 20px 50px -30px; padding: 26px 24px;">
      <div data-dc-tpl="490" style="font-size: 14px; letter-spacing: 0.06em; font-weight: 700; color: rgb(109, 40, 217); text-transform: uppercase;">Real results for real businesses</div>
      <div data-dc-tpl="491" style="margin-top: 22px; display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 18px;">
        
          <div data-dc-tpl="493" class="scpe" style="border-radius: 14px; background: linear-gradient(160deg, rgb(246, 245, 252), rgb(242, 241, 250)); padding: 22px 20px; transition: 0.25s;">
            <div data-dc-tpl="494" style="font-size: clamp(30px, 3vw, 38px); font-weight: 800; letter-spacing: -0.035em; color: rgb(59, 23, 201); font-variant-numeric: tabular-nums;"><span class="sc-interp">70%</span></div>
            <div data-dc-tpl="495" style="margin-top: 8px; font-size: 16px; line-height: 1.45; color: rgb(58, 63, 94);"><span class="sc-interp">Less time on bookkeeping</span></div>
          </div>
        
          <div data-dc-tpl="493" class="scpe" style="border-radius: 14px; background: linear-gradient(160deg, rgb(246, 245, 252), rgb(242, 241, 250)); padding: 22px 20px; transition: 0.25s;">
            <div data-dc-tpl="494" style="font-size: clamp(30px, 3vw, 38px); font-weight: 800; letter-spacing: -0.035em; color: rgb(59, 23, 201); font-variant-numeric: tabular-nums;"><span class="sc-interp">99.9%</span></div>
            <div data-dc-tpl="495" style="margin-top: 8px; font-size: 16px; line-height: 1.45; color: rgb(58, 63, 94);"><span class="sc-interp">Uptime &amp; data reliability</span></div>
          </div>
        
          <div data-dc-tpl="493" class="scpe" style="border-radius: 14px; background: linear-gradient(160deg, rgb(246, 245, 252), rgb(242, 241, 250)); padding: 22px 20px; transition: 0.25s;">
            <div data-dc-tpl="494" style="font-size: clamp(30px, 3vw, 38px); font-weight: 800; letter-spacing: -0.035em; color: rgb(59, 23, 201); font-variant-numeric: tabular-nums;"><span class="sc-interp">10,000+</span></div>
            <div data-dc-tpl="495" style="margin-top: 8px; font-size: 16px; line-height: 1.45; color: rgb(58, 63, 94);"><span class="sc-interp">Businesses trust Snaarp Books</span></div>
          </div>
        
          <div data-dc-tpl="493" class="scpe" style="border-radius: 14px; background: linear-gradient(160deg, rgb(246, 245, 252), rgb(242, 241, 250)); padding: 22px 20px; transition: 0.25s;">
            <div data-dc-tpl="494" style="font-size: clamp(30px, 3vw, 38px); font-weight: 800; letter-spacing: -0.035em; color: rgb(59, 23, 201); font-variant-numeric: tabular-nums;"><span class="sc-interp">50+</span></div>
            <div data-dc-tpl="495" style="margin-top: 8px; font-size: 16px; line-height: 1.45; color: rgb(58, 63, 94);"><span class="sc-interp">Financial reports out of the box</span></div>
          </div>
        
      </div>
    </div>
  </div>
  <div data-dc-tpl="496" class="books-container" style="max-width: 1280px; margin: 0px auto; padding: 36px clamp(20px, 4vw, 48px) 0px;">
    <div data-dc-tpl="497" style="border-radius: 20px; background: rgb(243, 242, 250); border: 1px solid rgb(236, 235, 245); padding: 26px clamp(18px, 3vw, 40px) 30px;">
      <div data-dc-tpl="498" style="text-align: center; font-size: 14px; letter-spacing: 0.1em; font-weight: 600; color: rgb(90, 95, 125); text-transform: uppercase;">Works seamlessly with your favorite tools</div>
      <div data-dc-tpl="499" style="margin-top: 24px; display: flex; flex-wrap: wrap; justify-content: center; align-items: flex-start; gap: 18px 30px;">
        <div data-dc-tpl="500" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="501" class="scpf" style="width: 86px; height: 86px; border-radius: 14px; background: rgb(227, 245, 252); display: grid; place-items: center;"><span data-dc-tpl="502" style="width: 56px; height: 56px; border-radius: 50%; background: rgb(19, 181, 234); color: rgb(255, 255, 255); display: grid; place-items: center; font-weight: 600; font-size: 18px;">xero</span></span></div>
        <div data-dc-tpl="503" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="504" style="width: 86px; height: 70px; border-radius: 14px; background: rgb(243, 242, 250); display: grid; place-items: center;"><span data-dc-tpl="505" style="width: 50px; height: 50px; border-radius: 50%; background: rgb(44, 160, 28); color: rgb(255, 255, 255); display: grid; place-items: center; font-weight: 800; font-size: 22px; letter-spacing: -0.06em;">qb</span></span><span data-dc-tpl="506" style="font-size: 14px; color: rgb(42, 46, 77);">QuickBooks</span></div>
        <div data-dc-tpl="507" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="508" style="width: 92px; height: 86px; border-radius: 14px; background: rgb(255, 255, 255); display: grid; place-items: center; box-shadow: rgba(30, 20, 90, 0.04) 0px 4px 12px;"><span data-dc-tpl="509" style="font-weight: 800; font-size: 32px; letter-spacing: -0.04em; color: rgb(0, 214, 57);">Sage</span></span></div>
        <div data-dc-tpl="510" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="511" style="width: 80px; height: 70px; border-radius: 14px; background: rgb(239, 239, 251); display: grid; place-items: center;"><span data-dc-tpl="512" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 44px; line-height: 1; color: rgb(28, 124, 244);">air</span></span><span data-dc-tpl="513" style="font-size: 14px; color: rgb(42, 46, 77);">FreeAgent</span></div>
        <div data-dc-tpl="514" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="515" style="width: 80px; height: 70px; display: grid; place-items: center;"><span data-dc-tpl="516" style="position: relative; width: 40px; height: 40px;"><span data-dc-tpl="517" style="position: absolute; left: 0px; top: 6px; width: 28px; height: 34px; border: 4px solid rgb(228, 37, 39); border-radius: 5px;"></span><span data-dc-tpl="518" style="position: absolute; left: 12px; top: 0px; width: 28px; height: 34px; border: 4px solid rgb(249, 178, 29); border-radius: 5px; mix-blend-mode: multiply;"></span></span></span><span data-dc-tpl="519" style="font-size: 14px; color: rgb(42, 46, 77);">Zoho Books</span></div>
        <div data-dc-tpl="520" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="521" style="width: 84px; height: 70px; border-radius: 14px; background: rgb(239, 239, 251); display: grid; place-items: center;"><span data-dc-tpl="522" style="font-weight: 800; font-size: 28px; letter-spacing: -0.05em; color: rgb(99, 91, 255);">stripe</span></span><span data-dc-tpl="523" style="font-size: 14px; color: rgb(42, 46, 77);">Stripe</span></div>
        <div data-dc-tpl="524" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="525" style="width: 124px; height: 86px; border-radius: 14px; background: rgb(255, 255, 255); display: grid; place-items: center; box-shadow: rgba(30, 20, 90, 0.04) 0px 4px 12px;"><span data-dc-tpl="526" style="font-weight: 800; font-size: 19px; letter-spacing: -0.02em; color: rgb(28, 28, 28); font-family: Georgia, serif;">GoCardless</span></span></div>
        <div data-dc-tpl="527" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="528" style="width: 80px; height: 70px; display: grid; place-items: center;"><span data-dc-tpl="529" style="width: 36px; height: 46px; border-radius: 4px 12px 4px 4px; background: rgb(31, 164, 99); display: grid; place-items: center;"><span data-dc-tpl="530" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 26px; line-height: 1; color: rgb(255, 255, 255);">table_view</span></span></span><span data-dc-tpl="531" style="font-size: 14px; color: rgb(42, 46, 77);">Excel/CSV</span></div>
        <div data-dc-tpl="532" style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span data-dc-tpl="533" style="width: 80px; height: 70px; display: grid; place-items: center;"><span data-dc-tpl="534" style="width: 46px; height: 46px; border-radius: 50%; border: 3px solid rgb(29, 42, 58); display: grid; place-items: center; color: rgb(29, 42, 58);"><span data-dc-tpl="535" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 24px; line-height: 1;">account_balance</span></span></span><span data-dc-tpl="536" style="font-size: 14px; color: rgb(42, 46, 77);">HMRC</span></div>
        <a data-dc-tpl="537" href="#" style="height: 70px; display: flex; align-items: center; gap: 6px; font-size: 15px; color: rgb(90, 95, 125); font-weight: 500;"><span data-dc-tpl="538" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">add</span>Many more</a>
      </div>
    </div>
  </div></section>`;
export const BOOKS_REPORTS1_TEXTCOL = `<div data-dc-tpl="541" style="flex: 1 1 400px; min-width: 0px; max-width: 520px;">
      <div data-dc-tpl="542" style="font-size: 12px; letter-spacing: 0.16em; font-weight: 600; color: rgb(122, 127, 160); text-transform: uppercase;">Real-time insights</div>
      <h2 data-dc-tpl="543" style="margin: 16px 0px 0px; font-size: clamp(30px, 3.4vw, 42px); line-height: 1.12; letter-spacing: -0.03em; font-weight: 800;">Make Smarter Decisions<br data-dc-tpl="544"><span data-dc-tpl="545" style="color: rgb(124, 58, 237);">with Powerful Reports.</span></h2>
      <p data-dc-tpl="546" style="margin: 18px 0px 0px; font-size: 16.5px; line-height: 1.6; color: rgb(75, 80, 112); text-wrap: pretty;">Get detailed reports and real-time insights to understand your cash flow, track performance and plan for the future.</p>
      <div data-dc-tpl="547" style="margin-top: 20px; display: flex; flex-direction: column; gap: 11px;">
        
          <div data-dc-tpl="549" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="550" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="551" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Profit &amp; Loss reports</span></div>
        
          <div data-dc-tpl="549" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="550" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="551" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Balance sheet</span></div>
        
          <div data-dc-tpl="549" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="550" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="551" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">VAT &amp; tax reports</span></div>
        
          <div data-dc-tpl="549" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="550" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="551" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Customisable reports</span></div>
        
          <div data-dc-tpl="549" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="550" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="551" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Export to PDF, CSV &amp; Excel</span></div>
        
      </div>
      <button data-dc-tpl="552" class="scp4" style="white-space: nowrap; margin-top: 28px; height: 44px; padding: 0px 26px; border-radius: 9px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(124, 58, 237); color: rgb(255, 255, 255); font-weight: 600; font-size: 14.5px; cursor: pointer; display: flex; align-items: center; gap: 10px; box-shadow: rgba(124, 58, 237, 0.6) 0px 12px 24px -10px;">Explore Reports <span data-dc-tpl="553" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">arrow_forward</span></button>
    </div>`;
export const BOOKS_REPORTS2_TEXTCOL = `<div data-dc-tpl="620" style="flex: 1 1 380px; min-width: 0px; max-width: 500px;">
        <div data-dc-tpl="621" style="font-size: 12px; letter-spacing: 0.16em; font-weight: 600; color: rgb(122, 127, 160); text-transform: uppercase;">Get paid faster</div>
        <h2 data-dc-tpl="622" style="margin: 14px 0px 0px; font-size: clamp(28px, 3vw, 36px); line-height: 1.14; letter-spacing: -0.03em; font-weight: 800; color: rgb(18, 19, 74);">Send Invoices,<br data-dc-tpl="624">Get Paid <span data-dc-tpl="625" style="color: rgb(59, 43, 224);">Online.</span></h2>
        <p data-dc-tpl="626" style="margin: 16px 0px 0px; font-size: 15.5px; line-height: 1.6; color: rgb(75, 80, 112); text-wrap: pretty;">Create professional invoices in seconds, send them in one click and let customers pay online. Track what's paid, sent and overdue at a glance — and get paid up to twice as fast.</p>
        <div data-dc-tpl="627" style="margin-top: 18px; display: flex; flex-direction: column; gap: 10px;">
          
            <div data-dc-tpl="629" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="630" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="631" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Professional branded invoices</span></div>
          
            <div data-dc-tpl="629" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="630" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="631" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Online card &amp; bank payments</span></div>
          
            <div data-dc-tpl="629" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="630" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="631" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Automatic payment reminders</span></div>
          
            <div data-dc-tpl="629" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="630" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="631" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Recurring invoices on autopilot</span></div>
          
            <div data-dc-tpl="629" style="display: flex; align-items: center; gap: 12px; font-size: 15px; color: rgb(42, 46, 77); font-weight: 500;"><span data-dc-tpl="630" style="width: 20px; height: 20px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="631" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 14px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Real-time paid &amp; overdue tracking</span></div>
          
        </div>
        <button data-dc-tpl="632" class="scpg" style="white-space: nowrap; margin-top: 26px; height: 42px; padding: 0px 24px; border-radius: 9px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(74, 43, 232); color: rgb(255, 255, 255); font-weight: 600; font-size: 14px; cursor: pointer; display: flex; align-items: center; gap: 10px; box-shadow: rgba(74, 43, 232, 0.6) 0px 12px 24px -10px;">Create an Invoice <span data-dc-tpl="633" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1;">arrow_forward</span></button>
      </div>`;
export const BOOKS_AFTER_REPORTS = `<section data-dc-tpl="672" id="pricing" data-screen-label="Pricing" style="background: linear-gradient(rgb(250, 250, 254), rgb(244, 243, 251));">
  <div data-dc-tpl="673" class="books-container" style="max-width: 1280px; margin: 0px auto; padding: clamp(40px, 5vw, 56px) clamp(20px, 4vw, 48px) clamp(56px, 7vw, 80px); display: flex; flex-wrap: wrap; gap: 44px; align-items: flex-start;">
    <div data-dc-tpl="674" style="flex: 1 1 380px; min-width: 0px; max-width: 500px; padding-top: 6px;">
      <h2 data-dc-tpl="675" style="margin: 0px; font-size: clamp(32px, 3.6vw, 46px); line-height: 1.08; letter-spacing: -0.035em; font-weight: 800;">Everything You Need.<br data-dc-tpl="676"><span data-dc-tpl="677" style="color: rgb(124, 58, 237);">Nothing You Don’t.</span></h2>
      <div data-dc-tpl="678" style="margin-top: 28px; display: flex; flex-direction: column; gap: 15px;">
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Professional invoicing &amp; quotes</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Expense tracking &amp; receipt scanning</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Bank feeds &amp; automatic reconciliation</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Recurring invoices &amp; payments</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Multi-currency support</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">VAT, MTD, CIS &amp; tax compliance</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Bills, purchase orders &amp; vendor management</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Custom reports &amp; dashboards</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Customer &amp; vendor portals</span></div>
        
          <div data-dc-tpl="680" style="display: flex; align-items: center; gap: 14px; font-size: 16.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="681" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(34, 181, 94); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="682" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">User roles, approvals &amp; audit logs</span></div>
        
      </div>
      <div data-dc-tpl="683" style="margin-top: 36px; display: flex; align-items: flex-end; gap: 24px; flex-wrap: wrap;">
        <button data-dc-tpl="684" class="scp4" style="white-space: nowrap; height: 60px; padding: 0px 44px; border-radius: 10px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(124, 58, 237); color: rgb(255, 255, 255); font-weight: 600; font-size: 16px; cursor: pointer; display: flex; align-items: center; gap: 12px; box-shadow: rgba(124, 58, 237, 0.65) 0px 14px 30px -10px;">See All Features <span data-dc-tpl="685" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 20px; line-height: 1;">arrow_forward</span></button>
        <div data-dc-tpl="686" style="display: flex; align-items: flex-start; gap: 4px; margin-bottom: 6px;">
          <svg data-dc-tpl="687" width="40" height="54"><path data-dc-tpl="688" d="M6 4 C 2 22, 12 38, 34 44" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.6; stroke-linecap: round;"></path><path data-dc-tpl="689" d="M3 12 L6 3 L12 10" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.6; stroke-linecap: round; stroke-linejoin: round;"></path><path data-dc-tpl="690" d="M27 40 L35 44 L28 50" style="fill: none; stroke: rgb(124, 58, 237); stroke-width: 1.6; stroke-linecap: round; stroke-linejoin: round;"></path></svg>
          <span data-dc-tpl="691" style="font-family: Caveat, cursive; font-size: 24px; line-height: 1.1; color: rgb(124, 58, 237); transform: rotate(-6deg); display: block; font-weight: 600; margin-top: -10px;">Built for<br data-dc-tpl="692">UK businesses<br data-dc-tpl="693">(and beyond)</span>
        </div>
      </div>
    </div>
    <div data-dc-tpl="694" style="flex: 1.6 1 600px; min-width: 0px; border-radius: 24px; background: rgb(255, 255, 255); border: 1px solid rgb(236, 235, 245); box-shadow: rgba(40, 20, 130, 0.25) 0px 30px 70px -40px; padding: clamp(22px, 3vw, 32px);">
      <h3 data-dc-tpl="695" style="margin: 0px; font-size: clamp(24px, 2.4vw, 30px); font-weight: 800; letter-spacing: -0.025em;">Simple, Transparent Pricing</h3>
      <p data-dc-tpl="696" style="margin: 6px 0px 0px; font-size: 16px; color: rgb(75, 80, 112);">Choose the plan that fits your business.</p>
      <div data-dc-tpl="697" style="margin: 22px auto 0px; width: max-content; max-width: 100%; display: flex; align-items: center; gap: 4px; padding: 4px; border-radius: 14px; background: rgb(242, 241, 248);">
        <button data-dc-tpl="698" style="white-space: nowrap; height: 38px; padding: 0px 22px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; border-radius: 10px; font-size: 14.5px; font-weight: 600; cursor: pointer; background: rgb(255, 255, 255); color: rgb(11, 13, 42); box-shadow: rgba(30, 20, 90, 0.1) 0px 2px 8px; transition: 0.2s;">Monthly</button>
        <button data-dc-tpl="699" style="white-space: nowrap; height: 38px; padding: 0px 22px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; border-radius: 10px; font-size: 14.5px; font-weight: 600; cursor: pointer; background: transparent; color: rgb(107, 112, 144); box-shadow: none; transition: 0.2s;">Yearly</button>
        <span data-dc-tpl="700" style="height: 38px; padding: 0px 16px; border-radius: 10px; background: rgb(221, 247, 230); color: rgb(21, 128, 61); font-size: 14px; font-weight: 700; display: flex; align-items: center;">Save 20%</span>
      </div>
      <div data-dc-tpl="701" style="margin-top: 26px; display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; align-items: stretch;">
        <div data-dc-tpl="702" style="border-radius: 18px; background: rgb(247, 247, 251); border: 1px solid rgb(240, 239, 246); padding: 28px 18px 18px; display: flex; flex-direction: column; text-align: center; margin-top: 14px;">
          <div data-dc-tpl="703" style="font-size: 18px; font-weight: 700;">Free</div>
          <div data-dc-tpl="704" style="font-size: 13.5px; color: rgb(107, 112, 144); margin-top: 10px;">Perfect for getting started</div>
          <div data-dc-tpl="705" style="font-size: 40px; font-weight: 800; letter-spacing: -0.03em; margin-top: 22px; line-height: 1;">£0</div>
          <div data-dc-tpl="706" style="font-size: 14px; color: rgb(140, 144, 168); margin-top: 6px;">forever</div>
          <div data-dc-tpl="707" style="margin-top: 28px; display: flex; flex-direction: column; gap: 14px; text-align: left;">
            <div data-dc-tpl="709" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="710" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Up to 20 invoices/month</span></div><div data-dc-tpl="709" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="710" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Basic reports</span></div><div data-dc-tpl="709" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="710" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">1 user</span></div>
          </div>
          <button data-dc-tpl="711" class="scp6" style="white-space: nowrap; margin-top: auto; height: 56px; border-radius: 10px; border: 1.5px solid rgb(217, 208, 255); background: rgb(255, 255, 255); color: rgb(124, 58, 237); font-size: 16px; font-weight: 600; cursor: pointer; transform: translateY(0px);">Get Started</button>
        </div>
        <div data-dc-tpl="712" style="position: relative; border-radius: 18px; background: linear-gradient(rgb(243, 240, 255), rgb(248, 247, 255)); border: 2px solid rgb(155, 130, 255); padding: 34px 18px 18px; display: flex; flex-direction: column; text-align: center; box-shadow: rgba(124, 58, 237, 0.55) 0px 26px 50px -26px;">
          <span data-dc-tpl="713" style="position: absolute; top: -14px; left: 50%; transform: translateX(-50%); height: 28px; padding: 0px 14px; border-radius: 9px; background: rgb(124, 58, 237); color: rgb(255, 255, 255); font-size: 12.5px; font-weight: 700; display: flex; align-items: center; white-space: nowrap;">Most Popular</span>
          <div data-dc-tpl="714" style="font-size: 18px; font-weight: 700;">Standard</div>
          <div data-dc-tpl="715" style="font-size: 13.5px; color: rgb(107, 112, 144); margin-top: 10px;">Everything small businesses need</div>
          <div data-dc-tpl="716" style="font-size: 40px; font-weight: 800; letter-spacing: -0.03em; margin-top: 22px; line-height: 1;"><span class="sc-interp">£15</span></div>
          <div data-dc-tpl="717" style="font-size: 14px; color: rgb(140, 144, 168); margin-top: 6px;"><span class="sc-interp">per month</span></div>
          <div data-dc-tpl="718" style="margin-top: 28px; display: flex; flex-direction: column; gap: 14px; text-align: left;">
            <div data-dc-tpl="720" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="721" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Unlimited invoices</span></div><div data-dc-tpl="720" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="721" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Bank feeds</span></div><div data-dc-tpl="720" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="721" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">VAT &amp; MTD</span></div><div data-dc-tpl="720" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="721" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Customer portal</span></div><div data-dc-tpl="720" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="721" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Up to 3 users</span></div>
          </div>
          <button data-dc-tpl="722" class="scp4" style="white-space: nowrap; margin-top: 30px; height: 56px; border-radius: 10px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(124, 58, 237); color: rgb(255, 255, 255); font-size: 16px; font-weight: 600; cursor: pointer; box-shadow: rgba(124, 58, 237, 0.8) 0px 14px 26px -12px;">Start Free Trial</button>
        </div>
        <div data-dc-tpl="723" style="border-radius: 18px; background: rgb(247, 247, 251); border: 1px solid rgb(240, 239, 246); padding: 28px 18px 18px; display: flex; flex-direction: column; text-align: center; margin-top: 14px;">
          <div data-dc-tpl="724" style="font-size: 18px; font-weight: 700;">Professional</div>
          <div data-dc-tpl="725" style="font-size: 13.5px; color: rgb(107, 112, 144); margin-top: 10px;">For growing businesses</div>
          <div data-dc-tpl="726" style="font-size: 40px; font-weight: 800; letter-spacing: -0.03em; margin-top: 22px; line-height: 1;"><span class="sc-interp">£30</span></div>
          <div data-dc-tpl="727" style="font-size: 14px; color: rgb(140, 144, 168); margin-top: 6px;"><span class="sc-interp">per month</span></div>
          <div data-dc-tpl="728" style="margin-top: 28px; display: flex; flex-direction: column; gap: 12px; text-align: left;">
            <div data-dc-tpl="730" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="731" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">All Standard features</span></div><div data-dc-tpl="730" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="731" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Multi-currency</span></div><div data-dc-tpl="730" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="731" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Advanced reporting</span></div><div data-dc-tpl="730" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="731" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Project tracking</span></div><div data-dc-tpl="730" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="731" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Custom workflows</span></div><div data-dc-tpl="730" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(42, 46, 77);"><span data-dc-tpl="731" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 18px; line-height: 1; color: rgb(34, 181, 94);">check</span><span class="sc-interp">Unlimited users</span></div>
          </div>
          <button data-dc-tpl="732" class="scp6" style="white-space: nowrap; margin-top: auto; height: 56px; border-radius: 10px; border: 1.5px solid rgb(217, 208, 255); background: rgb(255, 255, 255); color: rgb(124, 58, 237); font-size: 16px; font-weight: 600; cursor: pointer;">Start Free Trial</button>
        </div>
      </div>
    </div>
  </div></section><section data-dc-tpl="733" style="position: relative; overflow: hidden; background: radial-gradient(600px 300px at 85% 30%, rgba(140, 100, 255, 0.55), rgba(140, 100, 255, 0) 70%), linear-gradient(100deg, rgb(42, 20, 168) 0%, rgb(59, 31, 214) 40%, rgb(27, 15, 114) 100%); color: rgb(255, 255, 255);">
  <div data-dc-tpl="734" class="books-container" style="max-width: 1280px; margin: 0px auto; padding: clamp(40px, 5vw, 52px) clamp(20px, 4vw, 48px); display: flex; flex-wrap: wrap; align-items: center; gap: 28px 40px;">
    <div data-dc-tpl="735" style="flex: 1 1 560px; min-width: 0px;">
      <h2 data-dc-tpl="736" style="margin: 0px; font-size: clamp(24px, 2.5vw, 32px); font-weight: 700; letter-spacing: -0.03em; line-height: 1.2;">Join thousands of businesses already growing with Snaarp Books.</h2>
      <p data-dc-tpl="737" style="margin: 10px 0px 0px; font-size: 17px; color: rgb(227, 224, 255);">Simple. Powerful. Affordable. Get started today and see the difference.</p>
      <div data-dc-tpl="738" style="margin-top: 22px; display: flex; flex-wrap: wrap; gap: 12px 34px;">
        
          <div data-dc-tpl="740" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255);"><span data-dc-tpl="741" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(139, 108, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="742" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">No credit card required</span></div>
        
          <div data-dc-tpl="740" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255);"><span data-dc-tpl="741" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(139, 108, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="742" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">14-day free trial</span></div>
        
          <div data-dc-tpl="740" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255);"><span data-dc-tpl="741" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(139, 108, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="742" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Full access to all features</span></div>
        
          <div data-dc-tpl="740" style="display: flex; align-items: center; gap: 10px; font-size: 14.5px; color: rgb(237, 235, 255);"><span data-dc-tpl="741" style="width: 22px; height: 22px; border-radius: 50%; background: rgb(139, 108, 255); display: grid; place-items: center; flex: 0 0 auto;"><span data-dc-tpl="742" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 15px; line-height: 1; color: rgb(255, 255, 255);">check</span></span><span class="sc-interp">Free setup support</span></div>
        
      </div>
    </div>
    <button data-dc-tpl="743" class="scph" style="white-space: nowrap; height: 72px; padding: 0px 48px; border-radius: 12px; border-width: medium; border-style: none; border-color: currentcolor; border-image: none; background: rgb(255, 255, 255); color: rgb(109, 40, 217); font-weight: 700; font-size: 18px; cursor: pointer; display: flex; align-items: center; gap: 12px; box-shadow: rgba(255, 255, 255, 0.12) 0px 0px 0px 6px, rgba(0, 0, 0, 0.5) 0px 20px 40px -16px;">Get Started Free <span data-dc-tpl="744" style="font-family: &quot;Material Symbols Rounded&quot;; font-size: 22px; line-height: 1;">arrow_forward</span></button>
  </div></section></div></div></div>`;
export const BOOKS_HERO_SECTION_STYLE = "position: relative; overflow: hidden; background: radial-gradient(900px 560px at 82% 30%, rgb(234, 228, 255) 0%, rgba(234, 228, 255, 0) 62%), radial-gradient(700px 420px at 0% 100%, rgb(242, 239, 255) 0%, rgba(242, 239, 255, 0) 70%), rgb(250, 250, 254);";
export const BOOKS_HERO_ROW_STYLE = "position: relative; max-width: 1280px; margin: 0px auto; padding: clamp(36px, 5vw, 56px) clamp(20px, 4vw, 48px) clamp(56px, 7vw, 88px); display: flex; flex-wrap: wrap; align-items: center; gap: 48px;";
