import Link from "next/link"
import type { ReactNode } from "react"
import {
  ArrowRight, Check, ChevronDown, ChevronRight,
  PenLine, RefreshCw,
  Send, Sparkles, WandSparkles,
} from "lucide-react"
import { Button } from "@/components/ai-compose/Button"
import { RealWorkSection } from "@/components/ai-compose/RealWorkSection"
import { InteractiveComposeDemo } from "@/components/ai-compose/InteractiveComposeDemo"
import { Price } from "@/components/currency/Price"

const faqs: { q: ReactNode; a: string }[] = [
  { q: "Which apps does AI Compose work in?", a: "Mail and Teams today, with more of the Stack coming." },
  { q: "Will it send messages without me checking?", a: "No — every draft is a starting point. Nothing sends until you review and hit send yourself." },
  { q: "Can I set a tone for my drafts?", a: "Yes — choose a default tone (friendly, formal, brief) and adjust it per message when needed." },
  { q: "Does it understand the conversation I’m replying to?", a: "Yes — replies are context-aware, drafted based on the thread you’re responding to." },
  { q: <>Is AI Compose included in the <Price amount={1} /> Starter plan?</>, a: "Yes — included in every plan, no add-on required." },
]

// Same brand icon assets used for these apps elsewhere on the site (see
// ProductsMegaMenu.tsx and the other product pages' "Works Across the
// Stack" strips), swapped in for the generic Lucide placeholders.
const appLinks = [
  { iconSrc: "/assets/icons/envelope.jpg", name: "Mail", text: "Focused email, beautifully simple" },
  { iconSrc: "/assets/icons/chat-bubbles.jpg", name: "Teams", text: "Keep every conversation moving" },
  { iconSrc: "/assets/icons/search.jpg", name: "Contacts", text: "Your relationships, organized" },
  { iconSrc: "/assets/icons/apps-kalender.jpg", name: "Kalender", text: "A calmer way to plan" },
]

function ComposeMockup({ compact = false }: { compact?: boolean }) {
  return <div className={`relative rounded-3xl border bg-card shadow-2xl ${compact ? "p-4" : "p-5 md:p-7"}`}>
    <div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2"><span className="size-2.5 rounded-full bg-primary"/><span className="size-2.5 rounded-full bg-border"/><span className="size-2.5 rounded-full bg-border"/></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold text-primary">AI Compose</span></div>
    <div className="flex flex-col gap-3 rounded-2xl border bg-background p-4"><span className="text-xs font-semibold text-muted-foreground">WHAT SHOULD I WRITE?</span><p className="text-sm font-medium">Follow up about the invoice, keep it friendly</p><Button size="sm" className="self-end rounded-full"><Sparkles data-icon="inline-start" />Generate</Button></div>
    <div className="mt-4 rounded-2xl bg-secondary p-4 md:p-5"><div className="mb-3 flex items-center gap-2 text-xs font-semibold text-primary"><WandSparkles className="size-4" />DRAFT READY</div><p className="text-sm leading-relaxed">Hi Alex,<br/><br/>Just a quick note to follow up on the invoice I sent last week. Let me know if you need anything else from me — happy to help.<br/><br/>Best,<br/>Grace</p><div className="mt-4 flex gap-2"><Button size="sm" className="rounded-full"><Check data-icon="inline-start" />Insert</Button><Button size="sm" variant="outline" className="rounded-full"><RefreshCw data-icon="inline-start" />Regenerate</Button></div></div>
  </div>
}

function SectionTitle({ eyebrow, title, text }: {eyebrow:string,title:string,text?:string}) { return <div className="mx-auto flex max-w-3xl flex-col items-center gap-4 text-center"><span className="rounded-full bg-secondary px-4 py-2 text-xs font-bold tracking-[.16em] text-primary">{eyebrow}</span><h2 className="text-balance text-3xl font-bold tracking-tight md:text-5xl">{title}</h2>{text && <p className="max-w-2xl text-pretty leading-relaxed text-muted-foreground">{text}</p>}</div> }

export function AIComposePage() {
 const steps = [[PenLine,"01","Say what you need","Type a quick prompt, or start from a message you’re replying to."],[WandSparkles,"02","AI Compose drafts it","Get a full first pass in your tone, ready to edit."],[Send,"03","Send, don’t start from scratch","Tweak a line or two, or send it as-is."]] as const
 return <div className="ai-compose min-h-screen overflow-hidden bg-background">
  <section className="relative border-b bg-secondary/50"><div className="page-grid absolute inset-0 opacity-60"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 py-20 md:py-28 lg:grid-cols-[.95fr_1.05fr] lg:px-10"><div className="flex flex-col items-start gap-7"><span className="rounded-full border bg-background px-4 py-2 text-xs font-bold tracking-[.14em] text-primary">COMMUNICATE · AI COMPOSE</span><h1 className="text-balance text-5xl font-bold leading-[1.02] tracking-tight md:text-7xl">Never stare at a <span className="text-primary">blank message again.</span></h1><p className="max-w-xl text-pretty text-lg leading-relaxed text-muted-foreground">Draft an email, a Teams reply, or a follow-up in seconds — AI Compose writes the first pass, you make it yours.</p><div className="flex flex-wrap gap-3"><Button className="h-12 rounded-full px-6">Start for <Price amount={1} />/month <ArrowRight data-icon="inline-end" /></Button><Button variant="outline" className="h-12 rounded-full px-6" render={<Link href="#steps" />}>See how it works</Button></div><p className="flex items-center gap-2 text-sm text-muted-foreground"><Check className="size-4 text-primary"/>GDPR compliant · No credit card required</p></div><InteractiveComposeDemo/></div></section>
  <section className="border-b"><div className="mx-auto flex max-w-7xl flex-col items-center gap-8 px-6 py-12 lg:px-10"><p className="text-xs font-bold tracking-[.18em] text-muted-foreground">WORKS ACROSS THE STACK</p><div className="grid w-full grid-cols-2 justify-items-center gap-x-4 gap-y-8 md:grid-cols-4">{appLinks.map(({iconSrc,name})=><div key={name} className="sec-logo-strip-tile"><span className="sec-logo-strip-icon-tile"><img src={iconSrc} alt="" aria-hidden="true" /></span><span className="sec-logo-strip-tile-label">Snaarp {name}</span></div>)}</div></div></section>
  <section><div className="mx-auto grid max-w-7xl divide-y border-x md:grid-cols-3 md:divide-x md:divide-y-0">{[["Seconds","from a one-line prompt to a full draft"],["Every app","Mail, Teams, and more, one AI Compose everywhere"],["0","blank-page moments"]].map(([v,l])=><div className="flex flex-col gap-2 p-8 text-center md:p-12" key={v}><strong className="text-4xl text-primary">{v}</strong><span className="text-sm text-muted-foreground">{l}</span></div>)}</div></section>
  <section id="steps" className="workflow-section border-y py-24">
    <div className="mx-auto max-w-7xl px-6 lg:px-10">
      <div className="flex flex-col items-start justify-between gap-8 border-b pb-10 md:flex-row md:items-end">
        <div className="flex max-w-3xl flex-col items-start gap-4"><span className="text-xs font-bold tracking-[.18em] text-primary">HOW IT WORKS · 01—03</span><h2 className="text-balance text-4xl font-bold tracking-tight md:text-6xl">From a rough thought to <span className="text-primary">ready to send.</span></h2></div>
        <p className="max-w-sm text-pretty text-sm leading-relaxed text-muted-foreground">One simple flow, built into the places you already write. You stay in control from first prompt to final send.</p>
      </div>
      <div className="workflow-rail relative grid gap-8 pt-10 md:grid-cols-3 md:gap-5">
        {steps.map(([Icon,n,t,d],i)=><article key={n} className="group relative flex flex-col">
          <div className="mb-3 flex items-center justify-between border-b pb-3 font-mono text-[11px] font-semibold tracking-[.14em] text-muted-foreground"><span>FIG {n}</span><span>{i===0?"INPUT":i===1?"COMPOSE":"REVIEW"}</span></div>
          <div className="relative flex min-h-80 items-center justify-center overflow-hidden rounded-3xl border bg-card p-6 transition-transform duration-300 group-hover:-translate-y-1 md:min-h-96">
            <span className="absolute left-5 top-5 flex size-9 items-center justify-center rounded-full border bg-background font-mono text-xs font-bold text-primary">{n}</span>
            {i===0 ? <div className="w-full max-w-64 rotate-[-2deg] rounded-2xl border bg-background p-4 shadow-xl"><div className="mb-5 flex items-center justify-between"><span className="text-[10px] font-bold tracking-widest text-muted-foreground">NEW MESSAGE</span><PenLine className="size-4 text-primary"/></div><div className="rounded-xl bg-secondary p-4"><p className="text-xs leading-relaxed">Follow up about the invoice, keep it friendly.</p><span className="mt-4 flex items-center gap-2 text-[10px] font-bold text-primary"><span className="size-1.5 rounded-full bg-primary"/>PROMPT READY</span></div></div> : null}
            {i===1 ? <div className="relative w-full max-w-64"><span className="absolute -right-3 -top-8 flex size-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-lg"><WandSparkles className="size-5"/></span><div className="rounded-2xl border bg-background p-5 shadow-xl"><span className="mb-4 block text-[10px] font-bold tracking-widest text-primary">DRAFTING IN YOUR TONE</span><div className="flex flex-col gap-2"><span className="h-2 w-3/4 rounded-full bg-foreground/15"/><span className="h-2 w-full rounded-full bg-foreground/10"/><span className="h-2 w-5/6 rounded-full bg-foreground/10"/><span className="h-2 w-2/3 rounded-full bg-foreground/10"/></div><div className="mt-5 flex gap-2"><span className="rounded-full bg-accent px-3 py-1 text-[10px] font-semibold text-accent-foreground">Friendly</span><span className="rounded-full border px-3 py-1 text-[10px] font-semibold">Brief</span></div></div></div> : null}
            {i===2 ? <div className="w-full max-w-64 rotate-[2deg] rounded-2xl border bg-background p-5 shadow-xl"><div className="mb-5 flex items-center gap-2 text-[10px] font-bold tracking-widest text-primary"><Check className="size-4"/>READY TO REVIEW</div><p className="text-xs leading-relaxed text-muted-foreground">Hi Alex, just a quick note to follow up on the invoice…</p><div className="mt-5 flex items-center gap-2"><span className="flex h-9 flex-1 items-center justify-center rounded-full bg-primary text-[10px] font-bold text-primary-foreground">INSERT DRAFT</span><span className="flex size-9 items-center justify-center rounded-full border"><RefreshCw className="size-3.5"/></span></div></div> : null}
          </div>
          <div className="flex gap-4 pt-6"><span className="font-mono text-xs font-bold text-primary">{n}</span><div><h3 className="text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{d}</p></div></div>
        </article>)}
      </div>
      <div className="mt-14 flex flex-col items-start justify-between gap-5 rounded-2xl border bg-card p-5 sm:flex-row sm:items-center"><p className="text-sm"><b>That&apos;s it.</b> No setup, no new workflow, no blank page.</p><Button className="rounded-full">Start for <Price amount={1} />/month <ArrowRight data-icon="inline-end"/></Button></div>
    </div>
  </section>
  <RealWorkSection />
  <section className="bg-secondary/50 py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-2 lg:px-10"><ComposeMockup compact/><div><span className="text-xs font-bold tracking-[.16em] text-primary">BEAT THE BLANK PAGE</span><h2 className="mt-4 text-balance text-4xl font-bold md:text-5xl">Stop staring at a blank message box.</h2><p className="mt-5 leading-relaxed text-muted-foreground">The hardest part of most emails and messages isn’t the content — it’s starting. AI Compose gets you past the blank page in seconds, in every app you already use.</p><div className="mt-8 flex flex-col gap-6">{[["One prompt, a full draft.","Describe what you need in a sentence — get a ready-to-edit message back."],["Context-aware replies.","Replying to a thread pulls in what’s already been said, so drafts actually make sense."],["Never sends without you.","Every draft is yours to edit, regenerate, or discard — AI Compose never sends on its own."]].map(([t,d],i)=><div className="flex gap-4" key={t}><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary font-bold text-primary-foreground">{i+1}</span><p className="text-sm leading-relaxed"><b>{t}</b> <span className="text-muted-foreground">{d}</span></p></div>)}</div></div></div></section>
  <section className="py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-2 lg:px-10"><div><span className="text-xs font-bold tracking-[.16em] text-primary">YOUR VOICE, AMPLIFIED</span><h2 className="mt-4 text-balance text-4xl font-bold md:text-5xl">Sound like you, every time.</h2><div className="mt-10 flex flex-col gap-8">{[["Set your tone once.","Friendly, formal, or brief — pick a default and every draft follows it."],["Adjust on the fly.","Ask for a shorter version, a warmer version, or a more direct one — right in the compose box."],["Consistent across the team.","Set a shared tone for support or sales replies so every message sounds like the same company."]].map(([t,d])=><div key={t} className="border-l-2 border-primary pl-5"><h3 className="font-bold">{t}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{d}</p></div>)}</div></div><div className="rounded-3xl border bg-secondary p-6 md:p-10"><div className="rounded-2xl border bg-card p-6 shadow-xl"><p className="mb-4 text-xs font-semibold text-muted-foreground">CHOOSE YOUR TONE</p><div className="flex flex-wrap gap-2">{["Friendly","Formal","Brief"].map((t,i)=><span key={t} className={`rounded-full px-4 py-2 text-sm font-semibold ${i===0?"bg-primary text-primary-foreground":"border"}`}>{t}</span>)}</div><div className="mt-8 flex items-start gap-3 rounded-xl bg-secondary p-4"><Sparkles className="mt-1 size-4 shrink-0 text-primary"/><p className="text-sm leading-relaxed">Hey Alex — just checking in on that invoice. No rush, but let me know if there’s anything you need from me!</p></div></div></div></div></section>
  <section className="max-w-7xl mx-auto px-6 py-24 lg:px-10"><SectionTitle eyebrow="QUESTIONS" title="AI Compose, answered."/><div className="mx-auto mt-12 max-w-3xl rounded-3xl border bg-card px-6">{faqs.map(({q,a},i)=><details key={a} open={i===0} className="group border-b last:border-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-6 font-semibold">{q}<ChevronDown className="size-5 shrink-0 transition group-open:rotate-180"/></summary><p className="pb-6 pr-8 text-sm leading-relaxed text-muted-foreground">{a}</p></details>)}</div></section>
  <section id="pricing" className="max-w-7xl mx-auto px-6 pb-24 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-center gap-7 rounded-4xl bg-primary px-6 py-16 text-center text-primary-foreground md:py-24"><span className="text-xs font-bold tracking-[.18em]">READY WHEN YOU ARE</span><h2 className="max-w-4xl text-balance text-4xl font-bold md:text-6xl">Never write a first draft alone again. <Price amount={1} /> to start.</h2><Button className="h-12 rounded-full bg-background px-6 text-foreground hover:bg-background/90">Start the Stack for <Price amount={1} /> <ChevronRight data-icon="inline-end"/></Button></div></section>
 </div>
}
